Controllers/StokAyarlariController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvdeEczane.Models;
namespace EvdeEczane.Controllers
{
    public class StokAyarlariController : Controller
    {
        EVDEECZANEEntities3 db = new EVDEECZANEEntities3();
        // GET: StokAyarlari
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Stoklarim()
        {
            var model = db.Stok.ToList();
            return View(model);
        }
        public ActionResult StokEkle()
        {
            List<SelectListItem> Marka = (from i in db.Marka.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.MarkaAdi,
                                                  Value = i.ID.ToString()
                                              }).ToList();
            ViewBag.Marka = Marka;
            List<SelectListItem> AltKategori = (from i in db.Menuler.Where(x => x.ParentID == null && x.AltMenuID != null ).ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.MenuAdi,
                                                  Value = i.ID.ToString()
                                              }).ToList();
            ViewBag.AltKategori = AltKategori;
            return View();
        }
        public ActionResult StokDetay(int ID)
        {
            List<SelectListItem> Marka = (from i in db.Marka.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.MarkaAdi,
                                              Value = i.ID.ToString()
                                          }).ToList();
            ViewBag.Marka = Marka;
            List<SelectListItem> AltKategori = (from i in db.Menuler.Where(x => x.ParentID == null && x.AltMenuID != null).ToList()
                                                select new SelectListItem
                                                {
                                                    Text = i.MenuAdi,
                                                    Value = i.ID.ToString()
                                                }).ToList();
            ViewBag.AltKategori = AltKategori;
            var model = db.Stok.Where(x => x.ID == ID).FirstOrDefault();
            return View(model);
        } 
        [HttpPost]
        public ActionResult UrunEkle(Stok p)
        {
            if (Request.Files.Count <= 1)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname = file.FileName;
                        p.StokResim = "/Resimler/StokResim/" + fname;
                        fname = Path.Combine(Server.MapPath("~/Resimler/StokResim/"), fname);
                        file.SaveAs(fname);

                    }
                    HttpPostedFileBase dosya = files[0];
                    string dosyaAdi = dosya.FileName;
                    var menu = db.Menuler.Where(x => x.ID == p.StokKategoriID).FirstOrDefault();
                    var Parentmenu = db.Menuler.Where(x => x.ID == menu.AltMenuID).FirstOrDefault();
                    db.Stok.Add(new Stok()
                    {
                        StokAdi = p.StokAdi,
                        StokAciklama = p.StokAciklama,
                        StokBakiye = p.StokBakiye,
                        StokBarkod = p.StokBarkod,
                        StokFiyat = p.StokFiyat,
                        StokKategoriID = p.StokKategoriID,
                        StokKodu = p.StokKodu,
                        StokMarkaID = p.StokMarkaID,
                        StokResim = p.StokResim,
                        StokTarih = DateTime.Now,
                        isIndirim = p.isIndirim,
                        IndirimliFiyat = p.IndirimliFiyat,
                        isTrend = p.isTrend,
                        isYeni = p.isYeni,
                        StokResimAdi = dosyaAdi,
                        ParentKategoriID = menu.AltMenuID,
                        AnaKategoriID = Parentmenu.ParentID
                    }) ;
                    try
                    {
                        db.SaveChanges();
                        //return Json("Başarılı");
                        return RedirectToAction("/StokEkle/");

                    }
                    catch (Exception e)
                    {
                        return Json("Hata " + e.Message);
                    }
                }
                catch (Exception ex)
                {
                    return Json("Hata " + ex.Message);
                }

            }
            else
            {
                var menu = db.Menuler.Where(x => x.ID == p.StokKategoriID).FirstOrDefault();
                var Parentmenu = db.Menuler.Where(x => x.ID == menu.AltMenuID).FirstOrDefault();
                db.Stok.Add(new Stok()
                {
                    StokAdi = p.StokAdi,
                    StokAciklama = p.StokAciklama,
                    StokBakiye = p.StokBakiye,
                    StokBarkod = p.StokBarkod,
                    StokFiyat = p.StokFiyat,
                    StokKategoriID = p.StokKategoriID,
                    StokKodu = p.StokKodu,
                    StokMarkaID = p.StokMarkaID,
                    StokTarih = DateTime.Now,
                    isIndirim = p.isIndirim,
                    IndirimliFiyat = p.IndirimliFiyat,
                    isTrend = p.isTrend,
                    isYeni = p.isYeni,
                    ParentKategoriID = menu.AltMenuID,
                    AnaKategoriID = Parentmenu.ParentID
                });
                try
                {
                    db.SaveChanges();
                    //return Json("Başarılı");
                    return RedirectToAction("/Index/");

                }
                catch (Exception e)
                {
                    return Json("Hata " + e.Message);

                    //return RedirectToAction("/Index");
                }
            }
        }
        public JsonResult StokSil(int ID)
        {
            db.Stok.Remove(db.Stok.Where(x => x.ID == ID).FirstOrDefault());
            db.SaveChanges();
            return Json("Başarılı");
        }
        [HttpPost]
        public ActionResult UrunGuncelle(Stok p)
        {
            if (Request.Files.Count <= 1 || Request.Files == null)
            {
                try
                {
                    var menu = db.Menuler.Where(x => x.ID == p.StokKategoriID).FirstOrDefault();
                    var Parentmenu = db.Menuler.Where(x => x.ID == menu.AltMenuID).FirstOrDefault();
                    var stok = db.Stok.Where(x => x.ID == p.ID).FirstOrDefault();
                    stok.IndirimliFiyat = p.IndirimliFiyat;
                    stok.isIndirim = p.isIndirim;
                    stok.isTrend = p.isTrend;
                    stok.isYeni = p.isYeni;
                    stok.StokMarkaID = p.StokMarkaID;
                    stok.StokAciklama = p.StokAciklama;
                    stok.StokAdi = p.StokAdi;
                    stok.StokBakiye = p.StokBakiye;
                    stok.StokBarkod = p.StokBarkod;
                    stok.StokFiyat = p.StokFiyat;
                    stok.StokKategoriID = p.StokKategoriID;
                    stok.StokKodu = p.StokKodu;
                    stok.ParentKategoriID = menu.AltMenuID;
                    stok.AnaKategoriID = Parentmenu.ParentID;
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        if (file.FileName == "")
                        {
                            string fname = stok.StokResimAdi;
                            //p.StokResim = "/Resimler/StokResim/" + fname;
                            //fname = Path.Combine(Server.MapPath("~/Resimler/StokResim/"), fname);
                            //file.SaveAs(fname);
                        }
                        else
                        {
                            string fname = file.FileName;
                            p.StokResim = "/Resimler/StokResim/" + fname;
                            fname = Path.Combine(Server.MapPath("~/Resimler/StokResim/"), fname);
                            file.SaveAs(fname);
                            stok.StokResim = p.StokResim;
                        }

                    }

                   
                    
                    
                    try
                    {
                        db.SaveChanges();
                        //return Json("Başarılı");
                        return RedirectToAction("/Stoklarim/");

                    }
                    catch (Exception e)
                    {
                        return Json("Hata " + e.Message);
                    }
                }
                catch (Exception ex)
                {
                    return Json("Hata : " + ex.Message);
                }

            }
            else
            {
                var menu = db.Menuler.Where(x => x.ID == p.StokKategoriID).FirstOrDefault();
                var Parentmenu = db.Menuler.Where(x => x.ParentID == menu.ID).FirstOrDefault();
                var stok = db.Stok.Where(x => x.ID == p.ID).FirstOrDefault();
                stok.IndirimliFiyat = p.IndirimliFiyat;
                stok.isIndirim = p.isIndirim;

Controllers/StokDetayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvdeEczane.Models;

namespace EvdeEczane.Controllers
{
    public class StokDetayController : Controller
    {
        EVDEECZANEEntities3 db = new EVDEECZANEEntities3();
        // GET: StokDetay
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StokDetay(int ID)
        {
            var model = db.Stok.Where(x => x.ID == ID).FirstOrDefault();
            return View(model);
        }
    }
}

Views/StokAyarlari/StokDetay.cshtml
@model EvdeEczane.Models.Stok
@{
    ViewBag.Title = "StokDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="input-group-basic">
    <div class="row">
        <!-- Basic -->
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Stok Ekle</h4>
                </div>
                <div class="card-body">
                    <form action="~/StokAyarlari/UrunGuncelle" method="post" enctype="multipart/form-data">

                        <label class="form-label">Stok Resmi</label>
                        <div class="input-group mb-2">
                            <div class="image-preview">
                                <img class="img-responsive img-thumbnail" id="Resim" src="@Model.StokResim" style="width: 352px; height: 200px;" />
                            </div>
                        </div>
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="input-group mb-2">
                            <input type="file" id="SelectImage" style="display: none" name="StokResim" />
                            <input type="button" class="btn btn-secondary waves-effect waves-float waves-light" value="Resim Ekle" id="AddImage" />
                        </div>
                        <label class="form-label">Stok Adı</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Stok Adi" name="StokAdi" value="@Model.StokAdi" aria-label="Stok Adi" />
                        </div>
                        <label class="form-label">Stok Kodu</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Stok Kodu" name="StokKodu" value="@Model.StokKodu" aria-label="Stok Kodu" />
                        </div>
                        <label class="form-label">Stok Barkodu</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Stok Barkodu" name="StokBarkod" value="@Model.StokBarkod" aria-label="Stok Barkodu" />
                        </div>
                        <label class="form-label">Stok Fiyatı</label>
                        <div class="input-group mb-2">
                            <span class="input-group-text">&#8378;</span>
                            <input type="text" class="form-control" placeholder="100" name="StokFiyat" value="@Model.StokFiyat" aria-label="Amount (to the nearest dollar)" />
                            <span class="input-group-text">.00</span>
                        </div>
                        <label class="form-label">Stok Adeti</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" name="StokBakiye" aria-label="1" value="@Model.StokBakiye" />
                        </div>
                        <label class="form-label">Stok Marka</label>
                        <div class="input-group mb-2">
                            @*@Html.DropDownListFor(model => model.CategoryID, (List<SelectListItem>)ViewBag.Categorys, new { @class = "form-control" })*@

                            @Html.DropDownListFor(m => m.StokMarkaID, (List<SelectListItem>)ViewBag.Marka, new { @class = "form-control", @name = "StokMarkaID", @value = Model.Marka.MarkaAdi })
                            @*<input type="hidden" name="StoreID" value="@Session["ID"]" />*@
                        </div>
                        <label class="form-label">Stok Kategorisi</label>
                        <div class="input-group mb-2">
                            @*@Html.DropDownListFor(model => model.CategoryID, (List<SelectListItem>)ViewBag.Categorys, new { @class = "form-control" })*@
                            @Html.DropDownListFor(m => m.StokKategoriID, (List<SelectListItem>)ViewBag.AltKategori, new { @class = "form-control", @name = "StokKategoriID", @value = Model.Menuler.MenuAdi })
                            @*<input type="hidden" name="StoreID" value="@Session["ID"]" />*@
                        </div>
                        <div class="input-group">
                            <div class="form-check form-check-inline">
                                <div class="mb-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="isTrend" id="isTrend" value="@Model.isTrend">
                                        <label class="form-check-label" for="flexCheckDefault1">Trend</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="input-group">
                            <div class="form-check form-check-inline">
                                <div class="mb-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="isYeni" id="isYeni" value="@Model.isYeni">
                                        <label class="form-check-label" for="flexCheckDefault1">Yeni</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="input-group">
                            <div class="form-check form-check-inline">
                                <div class="mb-0">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="isIndirim" id="isIndirim" value="@Model.isIndirim">
                                        <label class="form-check-label" for="flexCheckDefault1">İndirimli</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <label class="form-label">İndirimli Fiyat</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="" value="@Model.IndirimliFiyat" name="IndirimliFiyat" id="IndirimliFiyat" disabled />
                        </div>
                        <div class="input-group">
                            <span class="input-group-text">Stok Açıklaması</span>
                            <textarea class="form-control" aria-label="With textarea" name="StokAciklama">@Model.StokAciklama</textarea>
                        </div>
                        @*<input type="hidden" name="ID" value="@Model.ID" />*@
                        <div class="input-group">
                            <button class="btn btn-primary" type="submit">Kaydet</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section Adjs{
    <script>
        $('#AddImage').click(function () {
            $('#SelectImage').click();
        });
        $('#AddImage').click(function () {
            var imgElement = $(this).find("img").first();
            if (imgElement.length) {
                var fullPath = imgElement.attr('src');
                console.log(fullPath);
            }
        });
        $("#isTrend").change(function () {
            console.log($("#isTrend").val())
            if ($(this).prop("checked")) {
                $(this).val(true);
            } else {
                $(this).val(false);
            }
        });
        $("#isYeni").change(function () {
            if ($(this).prop("checked")) {
                $(this).val(true);
            } else {
                $(this).val(false);
            }
        });
        $("#isIndirim").change(function () {
            if ($(this).prop("checked")) {
                $(this).val(true);
                $("#IndirimliFiyat").removeAttr('disabled');
            } else {
                $(this).val(false);
                $("#IndirimliFiyat").attr('disabled', 'disabled');

            }
        });


        $(function () {
            jQuery.browser = {};
            jQuery.browser.msie = false;
            jQuery.browser.version = 0;
            if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
                jQuery.browser.msie = true;
                jQuery.browser.version = RegExp.$1;
            }
            $("#SelectImage").change(function () {
                $(".image-preview").html("");
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                if (regex.test($(this).val().toLowerCase())) {
                    if ($.browser.msie && parseFloat(jQuery.browser.version) <= 9.0) {
                        $(".image-preview").show();
                        $(".image-preview")[0].filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src = $(this).val();
                    }
                    else {
                        if (typeof (FileReader) != "undefined") {
                            $(".image-preview").show();
                            $(".image-preview").append("<img style= width:24.92rem;height:13.92rem;margin-top:50; />");
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $(".image-preview img").attr("src", e.target.result);
                            }
                            reader.readAsDataURL($(this)[0].files[0]);
                        } else {
                            alert("This browser does not support FileReader.");
                        }
                    }
                } else {
                    alert("Please upload a valid image file.");
                }
            });
        });



    </script>
}

Views/StokAyarlari/Stoklarim.cshtml
@using EvdeEczane.Models
@model List<Stok> 
@{
    ViewBag.Title = "Stoklarim";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row mt-4">
    <div class="col-12">
        <h5 class="mb-0">Stoklar</h5>
    </div><!--end col-->
</div><!--end row-->

<div class="row row-cols-xl-5 row-cols-lg-4 row-cols-md-2 row-cols-1">
    @foreach (var item in Model)
    {
        <div class="col mt-4">
            <div class="card shop-list border-0 overflow-hidden rounded">
                    <ul class="label list-unstyled mb-0">
                        @if (item.isTrend == true)
                        {
                            <li><a href="javascript:void(0)" class="badge badge-link rounded-pill bg-primary">Trend</a></li>
                        }
                        @if (item.isYeni == true)
                        {
                            <li><a href="javascript:void(0)" class="badge badge-link rounded-pill bg-warning">Yeni</a></li>
                        }
                        @if (item.isIndirim == true)
                        {
                            <li><a href="javascript:void(0)" class="badge badge-link rounded-pill bg-success">İndirimli</a></li>
                        }


                    </ul>
                    <div class="shop-image position-relative overflow-hidden">
                        <a href="/StokAyarlari/StokDetay/@item.ID"><img src="@item.StokResim" class="img-fluid" alt=""></a>
                        @*<a href="product-detail.html" class="overlay-work">
                <img src="~/AdminContent/assets/images/shop/product/s-1.jpg" class="img-fluid" alt="">
            </a>*@

                    </div>
                    <div class="card-body content p-3 border-top">
                        <a href="/StokAyarlari/StokDetay/@item.ID" class="text-dark product-name h6">@item.StokAdi</a>
                        <div class="d-flex justify-content-between mt-1">
                            @if (item.isIndirim == true)
                            {
                                <del><h6 class="text-dark small fst-italic mb-0 mt-1">@item.StokFiyat</h6></del>
                                <h6 class="text-dark small fst-italic mb-0 mt-1">@item.IndirimliFiyat</h6>
                            }
                            else
                            {
                                <h6 class="text-dark small fst-italic mb-0 mt-1">@item.StokFiyat</h6>
                            }


                        </div>
                    </div>
                    <input type="button" class="btn btn-danger" name="name" value="Stok Sil" onclick="StokSil(@item.ID)" />
            </div>
        </div><!--end col-->
    }
</div><!--end row-->

@section Adjs{
    <script>

         function StokSil(ID) {
             getValue("StokAyarlari/StokSil",
                { ID: ID},
                function (data, err) {
                    if (!data) {
                        return;
                    } else if (data == 'Başarılı') {
                        location.href = '@Url.Action("Stoklarim", "StokAyarlari")';
                    }
                    else if (data.indexOf('Hata') > -1) {
                        alert(data)
                    }
                });
        };
    </script>
}