Models/Marka.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marka()
        {
            this.Stok = new HashSet<Stok>();
        }
    
        public int ID { get; set; }
        public string MarkaAdi { get; set; }
        public string MarkaAciklama { get; set; }
        public string MarkaResim { get; set; }
        public Nullable<int> KategoriID { get; set; }
    
        public virtual Menuler Menuler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stok> Stok { get; set; }
    }
}

Controllers/MarkaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvdeEczane.Models;
namespace EvdeEczane.Controllers
{
    public class MarkaController : Controller
    {
        EVDEECZANEEntities3 db = new EVDEECZANEEntities3();

        // GET: Marka
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Markalar()
        {
            var model = db.Marka.ToList();
            return View(model);
        }
        public ActionResult MarkaEkle()
        {
            return View();
        }
        public ActionResult MarkaDetay(int ID)
        {
            var model = db.Marka.Where(x => x.ID == ID).FirstOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult MarkaaEkle(Marka p)
        {
            if (Request.Files.Count <= 1)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname = file.FileName;
                        p.MarkaResim = "/Resimler/Marka/" + fname;
                        fname = Path.Combine(Server.MapPath("~/Resimler/Marka/"), fname);
                        file.SaveAs(fname);

                    }
                    HttpPostedFileBase dosya = files[0];
                    string dosyaAdi = dosya.FileName;

                    db.Marka.Add(new Marka()
                    {
                        MarkaAdi = p.MarkaAdi,
                        MarkaAciklama = p.MarkaAciklama,
                        MarkaResim = p.MarkaResim
                    });
                    try
                    {
                        db.SaveChanges();
                        //return Json("Başarılı");
                        return RedirectToAction("/Markalar/");

                    }
                    catch (Exception e)
                    {
                        return Json("Hata " + e.Message);
                    }
                }
                catch (Exception ex)
                {
                    return Json("Hata " + ex.Message);
                }

            }
            else
            {
                db.Marka.Add(new Marka()
                {
                    MarkaAdi = p.MarkaAdi,
                    MarkaAciklama = p.MarkaAciklama
                });
                try
                {
                    db.SaveChanges();
                    //return Json("Başarılı");
                    return RedirectToAction("/Markalar/");

                }
                catch (Exception e)
                {
                    return Json("Hata " + e.Message);

                    //return RedirectToAction("/Index");
                }
            }
        }
        public JsonResult MarkaSil(int ID)
        {
            db.Marka.Remove(db.Marka.Where(x => x.ID == ID).FirstOrDefault());
            db.SaveChanges();
            return Json("Başarılı");
        }
        [HttpPost]
        public ActionResult MarkaGuncelle(Marka p)
        {
            if (Request.Files.Count <= 1 || Request.Files == null)
            {
                try
                {
                    var marka = db.Marka.Where(x => x.ID == p.ID).FirstOrDefault();
                    marka.MarkaAdi = p.MarkaAdi;
                    marka.MarkaAciklama = p.MarkaAciklama;
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        if (file.FileName == "")
                        {

                            string fname = marka.MarkaResim;
                            //System.IO.File.Delete(Server.MapPath(fname+file.FileName));
                            //p.SiteLogo = "/Resimler/Logo/" + fname;
                            //fname = Path.Combine(Server.MapPath("~/Resimler/Logo/"), fname);
                            //file.SaveAs(fname);
                        }
                        else
                        {
                            string fname = file.FileName;
                            p.MarkaResim = "/Resimler/Marka/" + fname;
                            fname = Path.Combine(Server.MapPath("~/Resimler/Marka/"), fname);
                            file.SaveAs(fname);
                            marka.MarkaResim= p.MarkaResim;
                        }

                    }




                    try
                    {
                        db.SaveChanges();
                        //return Json("Başarılı");
                        return RedirectToAction("/Markalar/");

                    }
                    catch (Exception e)
                    {
                        return Json("Hata " + e.Message);
                    }
                }
                catch (Exception ex)
                {
                    return Json("Hata : " + ex.Message);
                }

            }
            else
            {
                var marka = db.Marka.Where(x => x.ID == p.ID).FirstOrDefault();
                marka.MarkaAdi = p.MarkaAdi;
                marka.MarkaAciklama = p.MarkaAciklama;

                try
                {
                    db.SaveChanges();
                    //return Json("Başarılı");
                    return RedirectToAction("/Markalar/");

                }
                catch (Exception e)
                {
                    return Json("Hata " + e.Message);

                    //return RedirectToAction("/Index");
                }
            }
        }
    }
}

Views/Marka/MarkaDetay.cshtml
@model EvdeEczane.Models.Marka
@{
    ViewBag.Title = "MarkaDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="input-group-basic">
    <div class="row">
        <!-- Basic -->
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Marka Güncelle</h4>
                </div>
                <div class="card-body">
                    <form action="~/Marka/MarkaGuncelle" method="post" enctype="multipart/form-data">

                        <label class="form-label">Marka Resmi</label>
                        <div class="input-group mb-2">
                            <div class="image-preview">
                                <img class="img-responsive img-thumbnail" id="Resim" src="@Model.MarkaResim" style="width: 352px; height: 200px;" />
                            </div>
                        </div>
                        <div class="input-group mb-2">
                            <input type="file" id="SelectImage" style="display: none" name="MarkaResim" />
                            <input type="button" class="btn btn-secondary waves-effect waves-float waves-light" value="Resim Ekle" id="AddImage" />
                        </div>
                        <label class="form-label">Marka Adı</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Marka Adı" name="MarkaAdi" aria-label="Marka Adi" value="@Model.MarkaAdi" />
                        </div>
                        <div class="input-group">
                            <span class="input-group-text">Marka Açıklaması</span>
                            <textarea class="form-control" aria-label="With textarea" name="MarkaAciklama">@Model.MarkaAciklama</textarea>
                        </div>
                        <input type="hidden" name="ID" value="@Model.ID" />
                        <div class="input-group">
                            <button class="btn btn-primary" type="submit">Kaydet</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section Adjs{
    <script>
        $('#AddImage').click(function () {
            $('#SelectImage').click();
        });
        $('#AddImage').click(function () {
            var imgElement = $(this).find("img").first();
            if (imgElement.length) {
                var fullPath = imgElement.attr('src');
                console.log(fullPath);
            }
        });



        $(function () {
            jQuery.browser = {};
            jQuery.browser.msie = false;
            jQuery.browser.version = 0;
            if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
                jQuery.browser.msie = true;
                jQuery.browser.version = RegExp.$1;
            }
            $("#SelectImage").change(function () {
                $(".image-preview").html("");
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                if (regex.test($(this).val().toLowerCase())) {
                    if ($.browser.msie && parseFloat(jQuery.browser.version) <= 9.0) {
                        $(".image-preview").show();
                        $(".image-preview")[0].filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src = $(this).val();
                    }
                    else {
                        if (typeof (FileReader) != "undefined") {
                            $(".image-preview").show();
                            $(".image-preview").append("<img style= width:24.92rem;height:13.92rem;margin-top:50; />");
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $(".image-preview img").attr("src", e.target.result);
                            }
                            reader.readAsDataURL($(this)[0].files[0]);
                        } else {
                            alert("This browser does not support FileReader.");
                        }
                    }
                } else {
                    alert("Please upload a valid image file.");
                }
            });
        });
    </script>
}

Views/Marka/MarkaEkle.cshtml
@{
    ViewBag.Title = "MarkaEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="input-group-basic">
    <div class="row">
        <!-- Basic -->
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Marka Ekle</h4>
                </div>
                <div class="card-body">
                    <form action="~/Marka/MarkaaEkle" method="post" enctype="multipart/form-data">

                        <label class="form-label">Marka Resmi</label>
                        <div class="input-group mb-2">
                            <div class="image-preview">
                                <img class="img-responsive img-thumbnail" id="Resim" src="" style="width: 352px; height: 200px;" />
                            </div>
                        </div>
                        <div class="input-group mb-2">
                            <input type="file" id="SelectImage" style="display: none" name="MarkaResim" />
                            <input type="button" class="btn btn-secondary waves-effect waves-float waves-light" value="Resim Ekle" id="AddImage" />
                        </div>
                        <label class="form-label">Marka Adı</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Marka Adı" name="MarkaAdi" aria-label="Marka Adi" />
                        </div>
                        <div class="input-group">
                            <span class="input-group-text">Marka Açıklaması</span>
                            <textarea class="form-control" aria-label="With textarea" name="MarkaAciklama"></textarea>
                        </div>
                        @*<input type="hidden" name="ID" value="@Model.ID" />*@
                        <div class="input-group">
                            <button class="btn btn-primary" type="submit">Kaydet</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section Adjs{
    <script>
        $('#AddImage').click(function () {
            $('#SelectImage').click();
        });
        $('#AddImage').click(function () {
            var imgElement = $(this).find("img").first();
            if (imgElement.length) {
                var fullPath = imgElement.attr('src');
                console.log(fullPath);
            }
        });
        


        $(function () {
            jQuery.browser = {};
            jQuery.browser.msie = false;
            jQuery.browser.version = 0;
            if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
                jQuery.browser.msie = true;
                jQuery.browser.version = RegExp.$1;
            }
            $("#SelectImage").change(function () {
                $(".image-preview").html("");
                var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                if (regex.test($(this).val().toLowerCase())) {
                    if ($.browser.msie && parseFloat(jQuery.browser.version) <= 9.0) {
                        $(".image-preview").show();
                        $(".image-preview")[0].filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src = $(this).val();
                    }
                    else {
                        if (typeof (FileReader) != "undefined") {
                            $(".image-preview").show();
                            $(".image-preview").append("<img style= width:24.92rem;height:13.92rem;margin-top:50; />");
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $(".image-preview img").attr("src", e.target.result);
                            }
                            reader.readAsDataURL($(this)[0].files[0]);
                        } else {
                            alert("This browser does not support FileReader.");
                        }
                    }
                } else {
                    alert("Please upload a valid image file.");
                }
            });
        });
    </script>
}

Views/Marka/Markalar.cshtml
@using EvdeEczane.Models
@model List<Marka>
@{
    ViewBag.Title = "Markalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row mt-4">
    <div class="col-12">
        <h5 class="mb-0">Markalar</h5>
        <a href="/Marka/MarkaEkle" class="btn btn-dark" style="float:right">Marka Ekle</a>
    </div><!--end col-->
</div><!--end row-->

<div class="row row-cols-xl-5 row-cols-lg-4 row-cols-md-2 row-cols-1">
    @foreach (var item in Model)
    {
        <div class="col mt-4">
            <div class="card shop-list border-0 overflow-hidden rounded">
                <div class="shop-image position-relative overflow-hidden">
                    <img src="@item.MarkaResim" class="img-fluid" alt="" style="min-height:200px;max-height:200px">
                    @*<a href="product-detail.html" class="overlay-work">
                            <img src="~/AdminContent/assets/images/shop/product/s-1.jpg" class="img-fluid" alt="">
                        </a>*@

                </div>
                <div class="card-body content p-3 border-top">
                    <a href="/Marka/MarkaDetay/@item.ID" class="text-dark product-name h6"> @item.MarkaAdi</a>
                    <div class="d-flex justify-content-between mt-1">
                        <span style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                            @item.MarkaAciklama
                        </span>
                    </div>
                </div>
                <input type="button" class="btn btn-danger" name="name" value="Marka Sil" onclick="MarkaSil(@item.ID)" />
            </div>
        </div><!--end col-->
    }
</div><!--end row-->
@section Adjs{
    <script>

         function MarkaSil(ID) {
             getValue("Marka/MarkaSil",
                { ID: ID},
                function (data, err) {
                    if (!data) {
                        return;
                    } else if (data == 'Başarılı') {
                        location.href = '@Url.Action("Markalar", "Marka")';
                    }
                    else if (data.indexOf('Hata') > -1) {
                        alert(data)
                    }
                });
        };
    </script>
}