Models/Kullanicilar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Adresler = new HashSet<Adresler>();
            this.Siparisler = new HashSet<Siparisler>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int ID { get; set; }
        public string KullaniciAdSoyad { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciSifre { get; set; }
        public string KullaniciCinsiyet { get; set; }
        public string KullaniciTel { get; set; }
        public Nullable<int> KullaniciAdresID { get; set; }
        public Nullable<System.DateTime> KullaniciDogumTarihi { get; set; }
        public string KullaniciTcKimlik { get; set; }
        public Nullable<System.DateTime> KullaniciSonGiris { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adresler> Adresler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}

Controllers/KullaniciAyarlariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvdeEczane.Models;
namespace EvdeEczane.Controllers
{
    public class KullaniciAyarlariController : Controller
    {
        EVDEECZANEEntities3 db = new EVDEECZANEEntities3();
        // GET: KullaniciAyarlari
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Kullanicilar()
        {
            var model = db.Kullanicilar.ToList();
            return View(model);
        }
        public JsonResult KullaniciSil(int ID)
        {
            db.Kullanicilar.Remove(db.Kullanicilar.Where(x => x.ID == ID).FirstOrDefault());
            db.SaveChanges();
            return Json("Başarılı");
        }
        public ActionResult AdminAyarlari()
        {
            var model = db.Admin.FirstOrDefault();
            return View(model);
        }
        public ActionResult AdminGuncelle(string KullaniciAdi,string KullaniciSifre, int ID)
        {
            var model = db.Admin.Where(x => x.ID == ID).FirstOrDefault();
            model.AdminKullaniciAdi = KullaniciAdi;
            model.AdminSifre = KullaniciSifre;
           
            try
            {
                db.SaveChanges();
                return Json("Başarılı");
            }
            catch (Exception)
            {
                return Json("Hata");
            }
        }
    }
}

Views/KullaniciAyarlari/AdminAyarlari.cshtml
@model EvdeEczane.Models.Admin
@{
    ViewBag.Title = "AdminAyarlari";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="input-group-basic">
    <div class="row">
        <!-- Basic -->
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Admin Ayarları</h4>
                </div>
                <div class="card-body">

                        <label class="form-label">Kullanıcı Adı</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Kullanıcı Adı" value="@Model.AdminKullaniciAdi" id="KullaniciAdi"/>
                        </div>
                        <label class="form-label">Kullanıcı Şifre</label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" placeholder="Kullanıcı Şifre"  value="@Model.AdminSifre" id="KullaniciSifre" />
                        </div>
                        <div class="input-group">
                            <button class="btn btn-primary" type="button" onclick="AdminGuncelle(@Model.ID)">Kaydet</button>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Adjs{
    <script>
         function AdminGuncelle(ID) {
             getValue("KullaniciAyarlari/AdminGuncelle",
                { ID: ID, KullaniciAdi: $("#KullaniciAdi").val(), KullaniciSifre: $("#KullaniciSifre").val() },
                function (data, err) {
                    if (!data) {
                        return;
                    } else if (data == 'Başarılı') {
                        location.href = '@Url.Action("AdminAyarlari", "KullaniciAyarlari")';
                    }
                    else if (data.indexOf('Hata') > -1) {
                        alert(data)
                    }
                });
        };

    </script>
    }

Views/KullaniciAyarlari/Kullanicilar.cshtml
@using EvdeEczane.Models
@model List<Kullanicilar> 
@{
    ViewBag.Title = "Kullanicilar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-center bg-white mb-0">
    <thead>
        <tr>
            <th class="border-bottom p-3">ID</th>
            <th class="border-bottom p-3" style="min-width: 220px;">Adı</th>
            <th class="text-center border-bottom p-3">Mail</th>
            <th class="text-center border-bottom p-3" style="">Şifre</th>
            <th class="text-center border-bottom p-3">Son Giriş</th>
            <th class="text-end border-bottom p-3" style="">Cinsiyet</th>
            <th class="text-center border-bottom p-3">Tel No</th>
            <th class="text-center border-bottom p-3">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th class="p-3">@item.ID</th>
                <td class="p-3">
                    <a href="#" class="text-primary">
                        <div class="d-flex align-items-center">
                            <span class="ms-2">@item.KullaniciAdSoyad</span>
                        </div>
                    </a>
                </td>
                <td class="text-center p-3">@item.KullaniciMail</td>
                <td class="text-center p-3">@item.KullaniciSifre</td>
                <td class="text-center p-3">@item.KullaniciSonGiris</td>
                <td class="text-center p-3">
                    <div class="badge bg-soft-danger rounded px-3 py-1">
                        @item.KullaniciCinsiyet
                    </div>
                </td>
                <td class="text-center p-3">
                    @item.KullaniciTel
                </td>
                <td class="text-end p-3">
                    <input type="button" class="btn btn-danger" name="name" value="Sil" onclick="KullaniciSil(@item.ID)" />
                </td>
            </tr>
        }
    </tbody>
</table>

@section Adjs{
    <script>
        function KullaniciSil(ID) {
            getValue("KullaniciAyarlari/KullaniciSil",
                { ID: ID},
                function (data, err) {
                    if (!data) {
                        return;
                    } else if (data == 'Başarılı') {
                        location.href = '@Url.Action("Kullanicilar", "KullaniciAyarlari")';
                    }
                    else if (data.indexOf('Hata') > -1) {
                        alert(data)
                    }
                });
        };
    </script>
    }